import './globals.css'
import { Poppins } from 'next/font/google'

const inter = Poppins({ subsets: ['latin'], weight: ['400'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import React from 'react'

export default function RootLayout({children}) {
  return (
    <html>

      <body className={inter.className}>{children}</body>
    </html>
    
  )
}

  